language: java
notifications:
  hipchat:
    rooms:
      secure: HMyBHnd4qaIjxqs0EW/JB63xv4vJZcQBpr/I7F6k6XEepIW6JjJ7P3wfXNJnbosjhGFm3RzQGAVsKPiVonMAlF1m+f3J0Mx4A4wJ1LO103maE/UCNbK3zB8sBUewjPg1eYQJ4/Wg86DowTkIDrE/XVZzNszpuXQp+cWPH6f6JVY=
deploy:
  provider: releases
  api_key:
    secure: RQ4uRENhSIaRngbulOhcK1mbML4j7Z2ahAw0Hqf5lrmKx0i0DoL4yE/485YOEdfFJuOpwiNKU/iNUv0IVu5reg2qcfoDRRGvD1sw8NETAFU+wSYHWKRFT37XYAzEtPo3BS0CDLfarRwUR5aO9AhqS2UCj6yzBarMPxBwnJoVoms=
  file: build/libs/sharepoint-plugin-1.0.jar
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/sharepoint-plugin
